language: go
go:
    - master
script:
    - go test -race -coverprofile=coverage.txt -covermode=atomic
after_success:
    - bash <(curl -s https://codecov.io/bash)
env:
    - CODECOV_TOKEN="037038aa-31ec-4600-936c-132be5f1bf09"
notifications:
  email:
    on_success: change
    on_failure: always
deploy:
    provider: heroku
    api_key:
      secure: "H5+2tqKRJiIdoJyI4no//x2S2pllbzJ6E9W8Yqz71SrD4wjZRZP8sTqWtJphKnUmXiaOBizDvS5n1GNVGkNr32fxKBhTUfuAj0OQmRu/kdvSQa3O+0QiQJwiyg92M0HfJ3fHULjKRMrIJ+BnxndJZGEsT868ASgcgZR45qmXqxNYL4dSKc92evB8rkIERsR16Efs/hnjcefCug32sKbF5AdmwSaKhaAmtSANAFU+dF+bYO5ZcTqUUbpEXBxnY7ovtduNAMlu5hK4QICejiT9MnrKY4UlWQNXk8PrUlo1PFSohEkcsBGJD5kOBzzJ6M7HfZ1ZwAgwFCR1GORD6U+SZ+p0TKUEg6rYUsKMuI8524YSlaRnO08VV51Xt8bPQ+PTmjA4Eg6JeEwTd7TTBPQ2SZB0/YALHKx7rUOhwtTnJjL2kHHceIM+G5I5FZJLnD4WZ8UNL+MZjUeI7pnkwIWvuoHeejKV19zbixzpw7vyQzIr1uQmMGcB8qjM4n/DC0D9RC00On21fBexJ9phIRop+tqDdgjnxNxD4CluozAfzzHKduDJ4WcK0vJOk+dnNObywFoXsGTKzgMs8ChoH/iu42FR04PEorsS5BnM5j8OEZsOC+YaWTfmIS/TtfKwu1rNlDh8UaR0GYOxNZmCa2S/aHtkOD88SNFRDoNGvJms7SA="
    app: noebs
    on:
      repo: adonese/noebs
