version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
  service-name:
    image: noebs
    environment:
    - GIN_MODE=release
    - PORT=8080